### ISSUE TITLE
[BUG] Crash when player respawned by SV_SpecPlayer during intermission

### ISSUE THREAD

**Issue by electricbrass** [odamex/odamex#1170]
**Describe the bug**
SV_SpecPlayer respawns dead players before turning them into spectators. This is a problem when someone becomes a spectator at just the wrong time, when there is no valid level loaded. This is most easily seen by lowering `sv_maxplayersperteam` because it currently forces all players to become spectators when set to 0 (which is it's own bug, 0 is unlimited so no one should become a spectator). When the cvars are unlatched at the start of the next map, if any players were dead when the intermission started, they will be respawned and invalid map data will be used, and the server will crash.

**Build that the bug occurred in**
11.0.0-prerelease.9792

**Expected behavior**
No crash

**Additional context**
This does NOT only occur when the cvar is changed during intermission as previously believed. It also seems to only occur when the maplist is in use.

**Comment by rakohus** [comment]
Fixed in 11.0

**Comment by electricbrass** [comment]
It is only partially fixed. It is much rarer now, but still possible to encounter, especially on a server with more players.
