### ISSUE TITLE
[BUG] Inconsistent Crusher / Conveyor Mechanics with gaiaaura.wad

### ISSUE THREAD

**Issue by Hekksy** [odamex/odamex#1187]
**Describe the bug**
For some reason the gimmick behind gaiaaura.wad does not work in Odamex. When you enter the map and go to the main room, conveyor belts bring in dead bodies to the center of the room to be sent elsewhere in the map to be respawned by arch-viles and then teleported back into the room. This enemy entering room mechanic lowers some sectors to allow the user to proceed through the rest of the map. The mechanics work fine in GZDoom and Woof, but in Odamex, for some reason the enemies either never spawn in, or only a few spawn in and then never spawn back in. Out of over 20 attempts, I was able to get monsters to spawn correctly twice, and even then the compatibility settings were inconsistent.  

**Build that the bug occurred in**
10.6 as well as 11 with DSDHacked branch.

**To Reproduce**
Launch gaiaaura.wad and start a new game to map01. Proceed to the first main golden room by shooting the first switch after spawning into the map. Once you pick up the yellow skull key, dead bodies killed by raising crushers should enter the room on conveyor belts. However, sometimes they never spawn, some spawn, or rarely, work as intended.

**Expected behavior**
The key should trigger a consistent number of demons to spawn in killed, then get respawned and trigger some linedefs that allow the player to complete the rest of the map.

**Screenshots, NetDemos, & Crash Dumps**
https://cdn.discordapp.com/attachments/250157428455243777/1343456248548294756/GaiaAuraBehavior.mp4?ex=67bd56a1&is=67bc0521&hm=1691d3d66f78c96ee7cb7d837c0e7c4fb2e1a903585a9954462709ff0e734217&
A discord video that shows intended behavior (via Woof source port)

**Additional context**
https://www.doomworld.com/forum/topic/150384-gaia-aura-standalone-map-by-ar_e_en-now-on-idgames/?tab=comments#comment-2892412
Thread for the wad on /idgames

**Comment by Hekksy** [comment]
Found some information:

Correct behavior:
https://cdn.discordapp.com/attachments/250157428455243777/1343476859442040843/Correct_Behavior_Woof.mp4?ex=67bd69d3&is=67bc1853&hm=fb0f014492454ca75aa0db99677e9e01a62009d5db478c9c2cff0dd5f563a25f&
Odamex incorrect behavior:
https://cdn.discordapp.com/attachments/250157428455243777/1343478919738822688/Odamex_Monsters_Stuck.mp4?ex=67bd6bbf&is=67bc1a3f&hm=fd83c19ea0c771dbedae4e76cd69d14f64954e5c21c835c694f9c3d684e045e8&

Odamex monsters can gets stuck in each other when being resurrected, which halts the monsters being teleported into the room after being revived behind the scenes. Also, upward crushers in Woof kill much faster than in Odamex.

**Comment by rakohus** [comment]
Is this fixed in 11.1? There is a fix for archvile resurrections

**Comment by Hekksy** [comment]
The issue is not resolved. It appears to be an issue with how much damage is dealt to monsters via raising crusher floors.  The first screenshot is Odamex. The room still has monsters after picking up the yellow key and they are not scrolling into the teleporter. The second screenshot is Woof. The monsters die nearly instantly and then get scrolled into a teleporter.

<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/d682e2d8-1875-41ab-9658-dd779b9b0ea1" />

<img width="2559" height="1439" alt="Image" src="https://github.com/user-attachments/assets/94c748b3-0007-4273-b283-005b42702462" />

**Comment by Hekksy** [comment]
Fixing bug 1367 appears to have had good results for fixing this issue mostly, but the conveyor belts may still have some issues:
In DSDA The monster corpses come out along the moving floors staggered and across different areas of the map. In Odamex they tend to spawn in clumps. 

Odamex:
<img width="2560" height="1440" alt="Image" src="https://github.com/user-attachments/assets/b45ae3c2-9983-4562-a39c-d5e89045d48c" />

DSDA:
<img width="1679" height="1045" alt="Image" src="https://github.com/user-attachments/assets/9e6f0994-f64e-4e6a-931f-aa2e575b4555" />
