### ISSUE TITLE
[BUG] Odamex sometimes doesn't realize a player has disconnected.

### ISSUE THREAD

**Issue by leximayfield** [odamex/odamex#423]
**Describe the bug**
If you repeatedly disconnect and reconnect to a game from the same IP, sometimes you will get "Unknown client message 163" on the server and "Got unknown challenge while connecting, disconnecting" on the client.

**Build that the bug occurred in**
10.0-protobreak.

**To Reproduce**
Connect to a local server, then kill the client process ungracefully and reconnect from a fresh one.

**Expected behavior**
No such messages should show up.

**Additional context**
If the client dies without gracefully disconnecting it appears that the server does not realize that the connection was severed and that the newly connecting client is in fact a newly connecting client, and not a continuation of the previous connection.  Client message 163 is actually the first byte of the client challenge.

**Comment by Ch0wW** [comment]
I would like to add the fact the bug also happens in 0.9.3.

**Comment by rakohus** [comment]
Verified behavior.

**Comment by CurrentResident** [comment]
For Odamex 13, this is largely addressed by the following PRs:

[Service reliable channels until idle when gracefully disconnecting](https://github.com/odamex/odamex/pull/1634)

- Ensures server knows when the client understands that it must disconnect or that the client initiated the disconnect, gracefully or ungracefully

[Reliable client --> server channel for player-initiated commands](https://github.com/odamex/odamex/pull/1588)

- Many changes...  This branch fell victim to scope growth, but one of the changes was the addition of a TCP "canary" socket that allows the client's OS to notify the server of ungraceful disconnect via sudden teardown.  It also enables TCP Keepalive to ensure that the socket has traffic every 10 seconds.  This also allows the server to detect when a client goes 100% unresponsive (hard lock, network link dropped, etc), though it takes up to 10 seconds to trigger.

**Comment by drivingspectrum** [comment]
This could be considered closed as it is an old protobreak bug after all, but because it can still occur in stable (12 series), I will leave this open until protobreak gets merged in eventually.
